/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/species": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SpeciesPage */
        get: operations["getSpecies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/species/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SpeciesSuggestions */
        get: operations["getSpeciesSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/species/{gbif_accepted_id}/cells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SpeciesCells */
        get: operations["getSpeciesCells"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cells/{h3_index}/species": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** CellSpecies */
        get: operations["getCellSpecies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CellBoundaryMembership */
        CellBoundaryMembership: {
            framework: string;
            framework_name: string;
            code: string;
            name: string;
        };
        /** CellDetailsResponse */
        CellDetailsResponse: {
            h3_index: string;
            resolution: number;
            boundaries?: components["schemas"]["CellBoundaryMembership"][];
            species?: components["schemas"]["CellSpeciesRow"][];
            stats?: components["schemas"]["CellStats"];
        };
        /** CellSpeciesRow */
        CellSpeciesRow: {
            gbif_accepted_id: string;
            iucn_sis_id: string | null;
            iucn_assessment_id: string | null;
            gbif_taxon_id: string | null;
            goat_taxon_id: string | null;
            species_name: string;
            family: string;
            redlist_category: string;
            dna_level: string;
        };
        /** CellStats */
        CellStats: {
            /** @default 0 */
            total: number;
            /** @default 0 */
            CR: number;
            /** @default 0 */
            EN: number;
            /** @default 0 */
            VU: number;
            /** @default 0 */
            NT: number;
            /** @default 0 */
            DD: number;
            /** @default 0 */
            LC: number;
            /** @default 0 */
            missing_species_dna: number;
            /** @default 0 */
            missing_genus_dna: number;
            /** @default 0 */
            missing_family_dna: number;
            /** @default 0 */
            goat_data_deficient: number;
        };
        /** HealthResponse */
        HealthResponse: {
            status: string;
            database: string;
            tiles: string;
        };
        /** SpeciesCellsResponse */
        SpeciesCellsResponse: {
            gbif_accepted_id: string;
            species_name: string;
            resolution: number;
            cells?: string[];
        };
        /** SpeciesPage */
        SpeciesPage: {
            rows?: components["schemas"]["SpeciesRow"][];
            /** @default 1 */
            page: number;
            /** @default 1 */
            total_pages: number;
            /** @default 0 */
            total: number;
            /** @default false */
            suggested: boolean;
        };
        /** SpeciesRow */
        SpeciesRow: {
            gbif_accepted_id: string;
            iucn_sis_id: string | null;
            iucn_assessment_id: string | null;
            gbif_taxon_id: string | null;
            goat_taxon_id: string | null;
            species_name: string;
            family: string;
            redlist_category: string;
            threat_score: number;
            dna_level: string;
            priority: number;
        };
        /** SpeciesSuggestion */
        SpeciesSuggestion: {
            gbif_accepted_id: string;
            species_name: string;
            family: string;
        };
        /** SpeciesSuggestions */
        SpeciesSuggestions: {
            rows?: components["schemas"]["SpeciesSuggestion"][];
            /** @default false */
            suggested: boolean;
        };
        /** StatsResponse */
        StatsResponse: {
            total: number;
            critically_endangered: number;
            edge_species: number;
            needs_dna_sampling: number;
            res3_cells: number;
            res7_cells: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    getSpecies: {
        parameters: {
            query?: {
                search?: string;
                sort?: string;
                order?: string;
                page?: number;
                per_page?: number;
                cr?: number;
                en?: number;
                vu?: number;
                nt?: number;
                dd?: number;
                lc?: number;
                sp?: number;
                gen?: number;
                fam?: number;
                gdd?: number;
                samp?: number;
                cov?: number;
                redlist?: string;
                dna?: string;
                systems?: string;
                admin0?: string;
                admin1?: string;
                municipality?: string;
                eez?: string;
                conservation_framework?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesPage"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    getSpeciesSuggestions: {
        parameters: {
            query?: {
                search?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesSuggestions"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    getSpeciesCells: {
        parameters: {
            query?: {
                resolution?: number;
            };
            header?: never;
            path: {
                gbif_accepted_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeciesCellsResponse"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
    getCellSpecies: {
        parameters: {
            query?: {
                resolution?: number;
                system?: string;
            };
            header?: never;
            path: {
                h3_index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellDetailsResponse"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status_code: number;
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                    };
                };
            };
        };
    };
}
