default:
    @just --list

sync:
    uv sync

clean:
    rm -rf __pycache__ .pytest_cache .ruff_cache __marimo__

pull:
    git pull

push:
    git add .
    git commit -m "Update"
    git push

reset:
    git reset --hard origin/main

upgrade:
    uv lock --upgrade
    uv sync
