<svelte:head><title>Tutorial · Ark-IV</title></svelte:head>

<main class="main-content">
  <div class="tutorial-container">
    <header class="tutorial-header"><h1>Tutorial</h1><p class="tutorial-intro">Learn how to use the table and map to explore species prioritization data.</p></header>

    <section class="tutorial-section">
      <h2>The Table</h2><p class="section-description">Explore species data row-by-row with search, sorting, pagination, and custom scoring.</p>
      <div class="tutorial-subsection layout-side-by-side is-visible"><div class="tutorial-content"><h3>Searching &amp; Filtering</h3><p>Use the search box to filter by species or family and quickly zero in on the records you need.</p><p>Open source records directly from the results: species names link to GBIF, IUCN status badges link to their Red List assessments, and DNA-gap badges link to GoaT. The external-link icon marks each one, and links open in a new tab.</p></div><figure class="tutorial-figure"><video class="feature-gif" autoplay loop muted playsinline aria-label="Searching and filtering the species table"><source src="/imgs/feat_search.mp4" type="video/mp4" /><a href="/imgs/feat_search.mp4">Download the searching and filtering clip.</a></video><figcaption>Type a species or family name to narrow results.</figcaption></figure></div>
      <div class="tutorial-subsection layout-single-column is-visible"><div class="tutorial-content"><h3>Sorting Columns</h3></div><figure class="tutorial-figure"><video class="feature-gif" autoplay loop muted playsinline aria-label="Sorting the species table"><source src="/imgs/feat_sorting_2.mp4" type="video/mp4" /><a href="/imgs/feat_sorting_2.mp4">Download the table sorting clip.</a></video><figcaption>Sort by threat level, DNA status, or priority score.</figcaption></figure><div class="tutorial-content"><p>Click any column heading to change the sort field. Click it again to reverse the order.</p></div></div>
      <div class="tutorial-subsection layout-split-header is-visible"><h3>Adjusting Scoring Weights</h3><div class="split-body"><div class="tutorial-content"><p>Open the sliders and customise how each IUCN threat level and DNA sampling status contributes to the priority score. Results update immediately.</p></div><figure class="tutorial-figure"><video class="feature-gif" autoplay loop muted playsinline aria-label="Adjusting species scoring weights"><source src="/imgs/feat_sliders.mp4" type="video/mp4" /><a href="/imgs/feat_sliders.mp4">Download the scoring weights clip.</a></video><figcaption>Change slider weights and see priorities recalculate.</figcaption></figure></div></div>
      <div class="tutorial-subsection layout-single-column is-visible"><div class="tutorial-content"><h3>Pagination</h3></div><figure class="tutorial-figure"><video class="feature-gif" autoplay loop muted playsinline aria-label="Moving between species table pages"><source src="/imgs/feat_pagination.mp4" type="video/mp4" /><a href="/imgs/feat_pagination.mp4">Download the pagination clip.</a></video><figcaption>Use the buttons to move between pages.</figcaption></figure></div>
      <div class="section-divider"><span>#</span></div>
    </section>

    <section class="tutorial-section">
      <h2>The Map</h2><p class="section-description">Visualize species distribution and priority across the global H3 grid.</p>
      <div class="tutorial-subsection layout-side-by-side is-visible"><div class="tutorial-content"><h3>Zooming &amp; Panning</h3><p>Drag to move around the world and use the scroll wheel or touchpad to zoom. The map automatically uses the finest resolution included in the current data build.</p></div><figure class="tutorial-figure"><video class="feature-gif" autoplay loop muted playsinline aria-label="Zooming and panning the map"><source src="/imgs/feat_movement.mp4" type="video/mp4" /><a href="/imgs/feat_movement.mp4">Download the map movement clip.</a></video><figcaption>Explore priorities from a worldwide overview down to the available cell detail.</figcaption></figure></div>
      <div class="tutorial-subsection layout-split-header is-visible"><h3>Color Intensity</h3><div class="split-body"><div class="tutorial-content"><p>Each cell's color represents its priority score, running from the low to the high end of the selected palette. Choose Turbo, Viridis, Cividis, or Inferno above the map; Viridis, Cividis, and Inferno are designed to remain readable with common forms of colour-vision deficiency. Enable species-count normalization to compare the average pressure per species instead of favouring cells simply because they contain more species.</p></div><figure class="tutorial-figure"><video class="feature-gif" autoplay loop muted playsinline aria-label="Map priority color intensity"><source src="/imgs/feat_heat.mp4" type="video/mp4" /><a href="/imgs/feat_heat.mp4">Download the color intensity clip.</a></video><figcaption>Brighter colors show higher-priority regions.</figcaption></figure></div></div>
      <div class="tutorial-subsection layout-single-column is-visible"><div class="tutorial-content"><h3>Hovering &amp; Details</h3></div><figure class="tutorial-figure"><video class="feature-gif" autoplay loop muted playsinline aria-label="Viewing map cell details"><source src="/imgs/feat_onehot.mp4" type="video/mp4" /><a href="/imgs/feat_onehot.mp4">Download the map details clip.</a></video><figcaption>Hover for aggregate values and click for species details.</figcaption></figure><div class="tutorial-content"><p>Hover over a hexagon to see its score. Clicking it opens conservation and DNA statistics plus the full species list for that cell.</p></div></div>
      <div class="tutorial-subsection layout-side-by-side layout-side-by-side--reverse is-visible"><div class="tutorial-content"><h3>Adjusting Weights in Real-Time</h3><p>Move any slider while viewing the map. The raw counts already in map tiles are rescored in the browser, so every visible cell recolors without a species-data request.</p></div><figure class="tutorial-figure"><video class="feature-gif" autoplay loop muted playsinline aria-label="Adjusting map weights in real time"><source src="/imgs/feat_heatsliders.mp4" type="video/mp4" /><a href="/imgs/feat_heatsliders.mp4">Download the live map weights clip.</a></video><figcaption>Move sliders to recalculate map priorities.</figcaption></figure></div>
      <div class="tutorial-subsection layout-single-column is-visible"><div class="tutorial-content"><h3>Extra Functionality</h3></div><figure class="tutorial-figure"><video class="feature-gif" autoplay loop muted playsinline aria-label="Using the map in fullscreen"><source src="/imgs/feat_fullscreen.mp4" type="video/mp4" /><a href="/imgs/feat_fullscreen.mp4">Download the fullscreen map clip.</a></video><figcaption>Use the full map area for detailed exploration.</figcaption></figure></div>
    </section>

    <div class="tutorial-subsection layout-single-column is-visible"><h3>Map View Shortcuts</h3><div class="tutorial-table-wrapper"><table class="tutorial-table"><thead><tr><th>Input</th><th>Action</th></tr></thead><tbody>
      <tr><td><strong>Mouse drag</strong></td><td>Pan the map</td></tr><tr><td><strong>Mouse scroll / pinch</strong></td><td>Zoom in or out</td></tr><tr><td><strong>Click cell</strong></td><td>Open its species details</td></tr><tr><td><strong>System buttons</strong></td><td>Switch between all, terrestrial, freshwater, and marine layers</td></tr>
    </tbody></table></div></div>

    <footer class="tutorial-footer"><p><strong>Ready to explore?</strong> Start with the <a href="/table">table</a> or jump to the <a href="/map">map</a>.</p></footer>
  </div>
</main>
